# src/localization.py

# English translations for UI elements and log messages
EN_TRANSLATIONS = {
    # GUI elements (src/gui.py)
    "app_title": "Easy AI Subtitle OCR",
    "menu_tools": "Tools",
    "menu_manage_cache": "Manage Cache...",
    "api_config_frame_text": "API Configuration",
    "google_api_key_label": "Google API Key:",
    "load_update_model_button": "Load/Update Model",
    "model_label": "Model:",
    "process_frame_text": "Process",
    "select_source_button": "1. Select Source (Video/XML/HTML)",
    "load_session_button": "Load Session...",
    "start_ocr_button": "2. Start OCR",
    "retry_failed_batches_button": "Retry Failed Batches",
    "status_label_initial": "...",
    "advanced_settings_frame_text": "Advanced Settings",
    "batch_size_label": "Batch Size:",
    "temperature_label": "Temperature:",
    "top_p_label": "Top-P:",
    "top_k_label": "Top-K:",
    "ocr_language_label": "OCR Language:",
    "navigation_save_frame_text": "Navigation & Save",
    "prev_button": "<< Previous",
    "nav_label_initial": "Sub 0 / 0",
    "next_button": "Next >>",
    "save_srt_button": "Save to .SRT file",
    "image_label_initial": "Subtitle Image Will Appear Here",
    "log_frame_text": "Log",

    # UI elements (src/ui_components.py)
    "select_subtitle_stream_dialog_title": "Select Subtitle Stream",
    "found_subtitle_streams_label": "Found image subtitle streams:",
    "ok_button": "OK",
    "select_session_dialog_title": "Select Session to Reload",
    "saved_sessions_label": "Saved sessions:",

    # Log messages and error strings (src/gui.py)
    "info_manage_cache_future": "Cache management feature will be developed in the future.",
    "info_retry_failed_future": "Retry failed batches feature will be developed in the future.",
    "info_advanced_settings_saved": "Advanced settings saved.",
    "warning_missing_info": "Please complete the steps.",
    "status_processing_ocr": "Processing OCR...",
    "status_ocr_complete": "OCR Complete! {count} subtitles.",
    "log_ocr_complete": "OCR Complete! Processed {count} subtitles.",
    "status_error": "Error: {message}",
    "log_ocr_error": "OCR Error: {message}",
    "error_ocr_title": "OCR Error",
    "log_navigating_to_subtitle": "Navigating to subtitle index {index}",
    "image_load_error_label": "Error loading image:\n{file}",
    "log_image_load_error": "Error loading image {file}: {error}",
    "warning_srt_save_cancelled": "SRT file save operation cancelled.",
    "log_saving_srt_to": "Saving SRT file to: {path}",
    "log_srt_save_success": "SRT file saved successfully.",
    "info_complete_title": "Complete",
    "info_srt_save_success": "SRT file saved successfully to:\n{path}",
    "log_srt_save_error": "Error saving SRT file: {error}",
    "error_title": "Error",
    "error_srt_save_failed": "Could not save SRT file: {error}",
    "error_api_key_title": "Error",
    "error_api_key_missing": "Please enter an API Key.",
    "status_loading_model": "Loading model...",
    "status_error_generic": "Error!",
    "status_ready_to_select_source": "Ready to select source.",
    "info_no_saved_sessions": "No saved sessions found.",
    "status_loading_session": "Loading session: {session}...",
    "error_load_session_title": "Error Loading Session",
    "status_session_load_failed": "Session load failed.",
    "log_model_changed": "Model changed to: {model}",
    "file_dialog_select_source_title": "Select Source: Video, XML, or HTML",
    "file_type_all_supported": "All Supported Files",
    "file_type_video": "Video Files",
    "file_type_timing": "Timing Files",
    "error_unsupported_file_format": "Unsupported file format.",
    "status_scanning_video": "Scanning: {file}...",
    "status_video_scan_failed": "Video scan failed.",
    "status_extracting_subtitles": "Extracting subtitles...",
    "status_extraction_complete": "Extraction complete! {count} subtitles. Ready for OCR.",
    "log_extraction_complete": "Extraction complete: found {count} subtitles.",
    "status_subtitle_stream_selection_cancelled": "Subtitle stream selection cancelled.",
    "status_processing_timing_images": "Processing timing file and images...",
    "status_timing_file_processing_failed": "Timing file processing failed.",
    "status_timing_file_loaded": "Loaded {count} subtitles! Ready for OCR.",
    "warning_missing_tools_title": "Missing Tools",
    "warning_missing_tools_message": "The following tools were not found in the system PATH:\n\n{tools}\n\nPlease install them and ensure they can be called from the command line.",

    # Log messages and error strings (src/app_context.py)
    "log_new_session_dir_created": "New session directory created: {path}",
    "log_session_cleanup_error": "Error cleaning up session directory: {error}",
    "log_session_cleaned_up": "Session directory cleaned up: {path}",
    "log_get_models_error": "Error getting model list: {error}",
    "log_timing_file_read_error_after_extraction": "Error reading timing file after extraction.",
    "log_extracting_subtitles_from": "Starting subtitle extraction from: {video_file}, stream index: {index}",
    "log_subtitle_extraction_error": "Subtitle extraction error: {error}",
    "log_loading_timing_file": "Loading timing file: {file}",
    "log_copying_images": "Copying images from {source} to session directory...",
    "log_images_copied": "Copied {count} images.",
    "error_unsupported_timing_file_format": "Unsupported timing file format (only .xml or .html).",
    "log_timing_file_loaded_success": "Successfully loaded {count} subtitles from timing file.",
    "log_timing_file_read_error_corrupt_empty": "Error reading timing file. File might be corrupt or empty.",
    "error_ocr_config_missing": "Missing configuration information to run OCR.",
    "log_starting_ocr_pipeline": "Starting OCR pipeline.",
    "log_loaded_batches_from_log": "Loaded {count} batches from log files. Ready to review and save.",
    "log_no_log_files_found": "No log files found in the selected session directory. Only original structure loaded.",
    "error_session_folder_not_exist": "Session folder does not exist.",
    "error_no_timing_file_in_session": "No timing file (.xml or .html) found in this session directory.",
    "error_unsupported_timing_file_format_session": "Unsupported timing file format.",
    "error_timing_file_read_error_session": "Error reading timing file in session. File might be corrupt or empty.",
    "warning_prompt_file_not_found": "prompt.txt not found. Using default prompt.",
    "error_reading_prompt_file": "Error reading prompt.txt: {error}. Using default prompt.",
    "default_ocr_prompt": "Extract text from image.",

    # Log messages and error strings (src/ocr.py)
    "log_getting_gemini_models": "Getting available Gemini models...",
    "warning_no_gemini_models_found": "No Gemini models found.",
    "error_no_gemini_models_found_check_key": "No Gemini models found. Please check API key and permissions.",
    "log_compatible_models_found": "Found {count} compatible models.",
    "log_get_models_api_error": "Error getting model list: {error}",
    "error_invalid_api_key_connection": "Invalid API Key or connection error: {error}",
    "warning_image_file_not_found": "File {path} not found. Skipping.",
    "error_no_images_to_process": "No images to process.",
    "error_api_no_content": "API returned no content.",
    "error_api_finish_reason": "Reason: {reason}.",
    "warning_json_parse_failed": "Could not parse JSON from response: {response_text}...",
    "error_prompt_blocked": "API blocked prompt due to safety policy violation: {error}",
    "error_gemini_api": "Gemini API error: {error}",
    "error_json_parse_api_response": "JSON parse error from API response: {error}. Raw response: {response_text}...",
    "error_unknown_api_call_json_parse": "Unknown error calling API or parsing JSON: {error}",
    "log_starting_ocr_process": "Starting OCR process...",
    "log_configuring_model": "Configuring model: {model_name}",
    "error_api_model_config": "API or model configuration error: {error}",
    "warning_batch_processing_error_retry": "Batch processing error from index {index}. Retrying attempt {attempt}/{max_retries} after {wait_time} seconds. Error: {error_message}",
    "error_api_result_not_list": "API result is not a list for batch starting from {index}.",
    "warning_invalid_result_item_in_batch": "Invalid result item in batch {index}: {result}. Skipping.",
    "warning_absolute_index_out_of_range": "Absolute index ({absolute_index}) out of range for batch {index}. Skipping.",
    "error_processing_result_item_in_batch": "Error processing a result item in batch {index}: {error}. Result: {result}",
    "error_batch_failed_after_retries": "Batch from index {index} failed after {max_retries} attempts. Last error: {error_message}",
    "log_failed_batches_recorded": "Recorded failed batches to settings.json: {failed_batches}",
    "ocr_complete_message": "Complete!",
    "log_error_parsing_saving_log": "Error parsing or saving log {filename}: {error}",
    "log_unknown_error_saving_log": "Unknown error saving log {filename}: {error}",

    # Log messages and error strings (src/utils.py)
    "log_xml_parse_error": "Error parsing XML file '{path}': {error}",
    "log_invalid_timecode_format": "Invalid timecode format: {timecode}. Error: {error}",
    "log_html_parse_error": "Error parsing HTML file '{path}': {error}",
    "warning_unknown_time_format": "Unknown time format: {time_string}",

    # Log messages and error strings (src/video_processor.py)
    "log_ffprobe_scan_docstring": "Uses ffprobe to scan video files and find image subtitle streams.",
    "error_no_image_subtitle_streams_found": "No image subtitle streams (PGS, VobSub) found in this video.",
    "error_ffprobe_not_found": "Error: `ffprobe` not found. Please install FFmpeg and add it to system PATH.",
    "error_video_scan_failed": "Error scanning video: {stderr}",
    "error_unknown_video_scan": "Unknown error: {error}",
    "log_mkvextract_bdsup2sub_docstring": "Uses mkvextract and BDSup2Sub to extract and convert subtitles.",
    "log_stage1_extracting_raw_stream": "Stage 1/2: Extracting raw subtitle stream from video...",
    "log_mkvextract_exit_code_error": "mkvextract exited with error code: {code}.",
    "error_mkvextract_failed_check_log": "Error running mkvextract. Please check log.",
    "warning_cannot_parse_progress_log": "Could not parse progress log: {line}",
    "error_mkvextract_error_message": "Error from mkvextract: {message}",
    "log_stage1_extraction_fast": "Stage 1 extraction was fast, no detailed progress reported.",
    "log_stage1_complete": "Stage 1 complete.",
    "error_mkvextract_not_found": "Error: `mkvextract` not found. Please install MKVToolNix and add it to PATH.",
    "error_mkvextract_unexpected": "Unexpected error running mkvextract: {error}",
    "error_mkvextract_details": "Error running mkvextract. Details: {error}",
    "error_bdsup2sub_file_not_found": "Error: File '{path}' not found. Please check settings.",
    "log_stage2_converting_subtitles": "Stage 2/2: Converting raw subtitles to images and timing file...",
    "log_bdsup2sub_exit_code_error": "BDSup2Sub exited with error code: {code}. Please check log.",
    "error_bdsup2sub_failed_check_log": "Error running BDSup2Sub. Please check log for details.",
    "log_bdsup2sub_complete_success": "BDSup2Sub completed successfully.",
    "error_bdsup2sub_no_xml_created": "Error: BDSup2Sub ran but did not create an XML file.",
    "error_java_not_found": "Error: `java` not found. Please install Java Runtime Environment (JRE).",
    "error_bdsup2sub_unexpected": "Unexpected error running BDSup2Sub: {error}",
    "error_bdsup2sub_details": "Error running BDSup2Sub. Details: {error}",
    "log_stage1_extracting_progress": "Stage 1: Extracting... {percent}%",
}
